# Generated by Django 5.1.7 on 2025-03-06 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
