# Generated by Django 5.1.7 on 2025-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realtors", "0002_rename_email_realtor_realtor_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realtor",
            old_name="realtor_email",
            new_name="email",
        ),
    ]
